services:
  - type: web
    name: brain-tumor-api
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    workingDir: backend
